#!/usr/bin/awk -f

#
# Script generates array of signals from <sys/signal.h>
#

BEGIN {
	num = 0;
}
{
	if (($1 ~ /^#define$/) && ($2 ~ /^SIG[A-Z]/) && \
	    ($2 !~ /^SIGRTMIN$/) && ($2 !~ /^SIGRTMAX$/) && \
	    ($2 !~ /^SIGSTKSZ$/) && ($2 !~ /^SIGEV_/) && \
	    ($3 > 0) && ($3 < 1000)) {
		signal[$3] = $2;
		if ($3 > num)
			num = $3;
	}
}
END {
	for (i = 0; i <= num; i++) {
		signame = signal[i];
		if (!signame)
			signame = "SIG_" i;
		printf("\t\"%s\",\t\t/* %d */\n", signame, i)
	}
}
