#!/usr/bin/awk -f

#
# Script generates array of syscalls from <sys/syscall.h>
#

BEGIN {
	num = 0;
}
{
	if (($1 ~ /^#define$/) && ($2 ~ /^SYS_/) && \
	    ($2 !~ /SYS_MAXSYSCALL/)) {
		syscall[$3] = substr($2, 5);
		if ($3 > num)
			num = $3;
	}
}
END {
	for (i = 0; i <= num; i++) {
		sysname = syscall[i];
		if (!sysname)
			sysname = i;
		printf("\t\"%s\",\t\t/* %d */\n", sysname, i)
	}
}
